export const SUBMIT_ENTRY_SUCCESS = 'SUBMIT_ENTRY_SUCCESS';
export const GET_ENTRIES_SUCCESS = 'GET_ENTRIES_SUCCESS';
export const EDIT_ENTRIES_SUCCESS = 'EDIT_ENTRIES_SUCCESS';
export const DELETE_ENTRY_SUCCESS = 'DELETE_ENTRY_SUCCESS';
export const SET_SEARCH_TEXT = 'SET_SEARCH_TEXT';